name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      run: npm install

    - name: Set variables
      run: echo "plugin-slug=dominant-color-async" >> $GITHUB_ENV

    - name: Build
      run: npx webpack -p
  
    - name: Build
      run: composer install --optimize-autoloader
  
    - name: Release
      run: |
        mkdir -p $plugin-slug
        rsync -av * $plugin-slug --exclude $plugin-slug --exclude node_modules --exclude .git --exclude .github --exclude .gitignore --exclude .editorconfig --exclude .prettierrc.js
        zip -r acf-image-aspect-ratio-crop.zip . -x *.git*
      
    - uses: actions/upload-artifact@master
      with:
        name: $plugin-slug.zip
        path: $plugin-slug.zip
            
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: $plugin-slug.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
